### ISSUE TITLE
Can run

### ISSUE THREAD

**Issue by ooTruffle** [AnonymusRaccoon/AnonymousGoose#1]
i go to run ./run.sh and i get bad interpriter no such file or directory

**Comment by zoriya** [comment]
Have you used the install command to get the project ? You will need bash, python3 and virtualenv (on a unix system) to run this project and if you did not runned the install command you won't have the dependencies installed.

**Comment by ooTruffle** [comment]
Cloning into 'AnonymousGoose'...
remote: Enumerating objects: 381, done.
remote: Counting objects: 100% (381/381), done.
remote: Compressing objects: 100% (250/250), done.
remote: Total 381 (delta 221), reused 276 (delta 119), pack-reused 0
Receiving objects: 100% (381/381), 9.05 MiB | 4.82 MiB/s, done.
Resolving deltas: 100% (221/221), done.
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/ReubenDollmanYT/Games/Linux Goose/AnonymousGoose/venv/bin/python2
Also creating executable in /home/ReubenDollmanYT/Games/Linux Goose/AnonymousGoose/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
sh: 6: source: not found
sh: 7: pip3: not found
sh: 8: ./run.sh: not found

**Comment by zoriya** [comment]
You seems to be using "sh" instead of bash for the installation script. Your shell needs to have the source builtin and yours don't. In most linux distro, /usr/bin/sh is an symlink to /usr/bin/bash and the shebang used in the install script is /usr/bin/bash. Have you modified the install shebang?
